CREATE TABLE Product
(
    ref   VARCHAR(255)     NOT NULL,
    name  VARCHAR(255)     NOT NULL,
    stock DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (ref)
);

CREATE TABLE Purchases
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_p     date                                    NOT NULL,
    quantity   DOUBLE PRECISION                        NOT NULL,
    product_id VARCHAR(255),
    CONSTRAINT pk_purchases PRIMARY KEY (id)
);

CREATE TABLE Sales
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_p     date                                    NOT NULL,
    quantity   DOUBLE PRECISION                        NOT NULL,
    product_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_sales PRIMARY KEY (id)
);

CREATE TABLE UserEntity
(
    email     VARCHAR(250) NOT NULL,
    firstName VARCHAR(250) NOT NULL,
    lastName  VARCHAR(200) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (email)
);

ALTER TABLE Product
    ADD CONSTRAINT uc_product_name UNIQUE (name);

ALTER TABLE Purchases
    ADD CONSTRAINT FK_PURCHASES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES Product (ref);

ALTER TABLE Sales
    ADD CONSTRAINT FK_SALES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES Product (ref);