CREATE TABLE Purchases
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dateP      TIMESTAMP WITHOUT TIME ZONE,
    quantity   DOUBLE PRECISION                        NOT NULL,
    product_id VARCHAR(255),
    CONSTRAINT pk_purchases PRIMARY KEY (id)
);

CREATE TABLE Sales
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date_p     date                                    NOT NULL,
    quantity   DOUBLE PRECISION                        NOT NULL,
    product_id VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_sales PRIMARY KEY (id)
);

CREATE TABLE UserEntity
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstName VARCHAR(250)                             NOT NULL,
    lastName  VARCHAR(200)                             NOT NULL,
    email     VARCHAR(250)                             NOT NULL,
    password  VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_userentity PRIMARY KEY (id)
);

ALTER TABLE UserEntity
    ADD CONSTRAINT uc_userentity_email UNIQUE (email);

ALTER TABLE Purchases
    ADD CONSTRAINT FK_PURCHASES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES Product (ref);

ALTER TABLE Sales
    ADD CONSTRAINT FK_SALES_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES Product (ref);

ALTER TABLE Product
ALTER
COLUMN name TYPE VARCHAR(255) USING (name::VARCHAR(255));